name: Build Cosmic ISOs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build_iso.yml'

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  INSTALLER_VERSION: 40

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name: [cosmic-silverblue, cosmic-base]
        image_tag: [40-amd64, rawhide-amd64]
            
    steps:
      - name: Build ISOs
        uses: jasonn3/build-container-installer@v1.2.0
        id: build
        with:
          arch: ${{ contains(matrix.image_tag, 'amd64') && 'x86_64' || 'arm64' }}
          image_name: ${{ matrix.image_name }}
          image_repo: ghcr.io/ublue-os
          enable_flatpak_dependencies: false
          # We cannot use Silverblue variant since we need the user creation options in anaconda
          variant: 'Kinoite'
          version: ${{ env.INSTALLER_VERSION }}
          image_tag: ${{ matrix.image_tag }}
          secure_boot_key_url: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          enrollment_password: 'ublue-os'
          iso_name: ${{ matrix.image_name }}-${{ steps.generate-tag.outputs.tag }}

      - name: Upload ISOs and Checksum to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}-${{ matrix.image_tag }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
